Use explicit constructors for structs that have constructors. Open-source vesions of G++ seem to require this. Before this change I was getting errors such as:
    	error: braces around scalar initializer for type 'const pagespeed::image_compression::GoldImageCompressionInfo'